#!/bin/sh
# live-build configuration script
# see 'man lb config'

lb config noauto \
--apt-recommends false \
--apt-indices false \
--architectures amd64 \
--archive-areas 'main contrib non-free non-free-firmware' \
--backports true \
--security true \
--updates true \
--source false \
--binary-filesystem ext4 \
--binary-images iso-hybrid \
--checksums sha256 \
--chroot-squashfs-compression-type zstd \
--clean \
--color \
--debconf-frontend noninteractive \
--debian-installer none \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--distribution bookworm \
--firmware-binary true \
--firmware-chroot true \
--initramfs live-boot \
--iso-publisher debian-live-config \
--iso-volume debian-live-config-4.2.0 \
--image-name debian-live-confiso \
--linux-packages "linux-image linux-headers" \
--bootappend-live "boot=live config nopersistence noeject timezone=America/Toronto splash" \
--uefi-secure-boot enable \
--memtest memtest86+ \
--win32-loader false

"${@}"
